name: Build and Release

on:
  push:
    tags:
      - 'v*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run make  # Replace with your build command

    - name: App location
      id: app_location
      run: |
        echo "tagname=$(echo $GITHUB_REF | sed 's|refs/tags/||')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ./out/make/*.dmg
        tag_name: ${{ steps.app_location.outputs.tagname }}
        name: Release ${{ steps.app_location.outputs.tagname }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
